### ISSUE TITLE
[feature request] Soft lock condition scale

### ISSUE THREAD

**Issue by melMass** [Bismuth-Consultancy-BV/MLOPs#100]
ControlNet create `condition scale` is hard locked to 1, IMO this should be soft locked

Here for instance I'm trying to implement `Reference only` (which should actually work by just providing an image to controlnet create without any condition but the results I have don't match the SD webui extension which is not trivial to isolate)

| Reference | Scale 0 | Scale 1 | Scale 1.5 |
| --------- | ------- | ------- | --------- |
| ![image](https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/7041726/87320bf7-920d-4e69-9389-7ea620df3554)  |  ![image](https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/7041726/fd550555-ba1f-4032-bf45-daebe60b5234)       |    ![image](https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/7041726/d36bda18-4a94-46cf-9c4c-1dd2477f4dbb) | ![image](https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/7041726/b738d689-caf8-4afa-a2c0-aab183628fa8)   |

**Comment by Ambrosiussen** [comment]
Fixed!
