### ISSUE TITLE
Apple M1 Max

### ISSUE THREAD

**Issue by Eranio-bit** [Bismuth-Consultancy-BV/MLOPs#101]
This is he error I am getting.
Houdini 19.5.556 for M1

Traceback (most recent call last):
  File "mlops_install", line 5, in <module>
  File "/Users/eranio.petruska/Documents/MLOPs-main/scripts/python/mlops_utils.py", line 125, in install_mlops_dependencies
    pip_install(hou.text.expandString("$MLOPS/requirements.txt"), True, True)
  File "/Users/eranio.petruska/Documents/MLOPs-main/scripts/python/mlops_utils.py", line 301, in pip_install
    raise hou.Error(res[1].decode())
hou.Error: Error: Couldn't remove old operator type definition sesi_temporary::Sop/subnet
  Running command git clone --filter=blob:none --quiet https://github.com/patrickvonplaten/controlnet_aux /private/var/folders/7q/49_cld7x40n91zpmbk6pkz2wywj59k/T/pip-install-09n8te7y/controlnet-aux_f0214a217491437693f517d3f31fc209
  Running command git rev-parse -q --verify 'sha^845161d1deac8c4f0a8f9df0c9dc355fcc2d0830'
  Running command git fetch -q https://github.com/patrickvonplaten/controlnet_aux 845161d1deac8c4f0a8f9df0c9dc355fcc2d0830
  Running command git checkout -q 845161d1deac8c4f0a8f9df0c9dc355fcc2d0830
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/diffusers /private/var/folders/7q/49_cld7x40n91zpmbk6pkz2wywj59k/T/pip-install-09n8te7y/diffusers_fcaf2cee44724c188b6321f35e7ee4cd
  Running command git rev-parse -q --verify 'sha^2858d7e15eaf445ec37fc77b204a85f84affbeef'
  Running command git fetch -q https://github.com/huggingface/diffusers 2858d7e15eaf445ec37fc77b204a85f84affbeef
  Running command git checkout -q 2858d7e15eaf445ec37fc77b204a85f84affbeef
ERROR: Could not find a version that satisfies the requirement xformers==0.0.19 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.16rc424, 0.0.16rc425, 0.0.16, 0.0.20, 0.0.21.dev543, 0.0.21.dev544, 0.0.21.dev546, 0.0.21.dev547)
ERROR: No matching distribution found for xformers==0.0.19

**Comment by ChrisFriendly** [comment]
anyone found a solution for this issue yet?

**Comment by Ambrosiussen** [comment]
Try updating MLOPs and try again!
