### ISSUE TITLE
Diffusers v0.17.0 

### ISSUE THREAD

**Issue by tuckerhcool** [Bismuth-Consultancy-BV/MLOPs#102]
Latest version of Diffusers is running some new and expanded features, one of which is support for Torch 2.0. As a result, there is massive improvements in the inference speed of the most popular pipelines. I would like to ask that MLOPs get updated to this version to take advantage of some of the new features and support added in this new version.

Here are the release notes for more information:
https://github.com/huggingface/diffusers/releases/tag/v0.17.0

**Comment by melMass** [comment]
This also support Lora safe tensors I believe
