### ISSUE TITLE
Install Dependencies - ERROR: No matching distribution found for xformers==0.0.19

### ISSUE THREAD

**Issue by mph101** [Bismuth-Consultancy-BV/MLOPs#103]
Running the Install Dependencies Tool I'm having the following error (Houdini19.5.605 / Python3.9.10):

Running command git clone --filter=blob:none --quiet https://github.com/patrickvonplaten/controlnet_aux /private/var/folders/91/55c2dvcx6yv0sv99hb1t0b840000gn/T/pip-install-_nmfoml7/controlnet-aux_b8a7a0157825493c8a091b45aff89d78
  Running command git rev-parse -q --verify 'sha^845161d1deac8c4f0a8f9df0c9dc355fcc2d0830'
  Running command git fetch -q https://github.com/patrickvonplaten/controlnet_aux 845161d1deac8c4f0a8f9df0c9dc355fcc2d0830
  Running command git checkout -q 845161d1deac8c4f0a8f9df0c9dc355fcc2d0830
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/diffusers /private/var/folders/91/55c2dvcx6yv0sv99hb1t0b840000gn/T/pip-install-_nmfoml7/diffusers_daecb0d3594647609d7867e0a61ad7f4
  Running command git rev-parse -q --verify 'sha^2858d7e15eaf445ec37fc77b204a85f84affbeef'
  Running command git fetch -q https://github.com/huggingface/diffusers 2858d7e15eaf445ec37fc77b204a85f84affbeef
  Running command git checkout -q 2858d7e15eaf445ec37fc77b204a85f84affbeef
ERROR: Could not find a version that satisfies the requirement xformers==0.0.19 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.16rc424, 0.0.16rc425, 0.0.16, 0.0.20, 0.0.21.dev544, 0.0.21.dev546, 0.0.21.dev547, 0.0.21.dev548)
ERROR: No matching distribution found for xformers==0.0.19

Thanks

**Comment by Ambrosiussen** [comment]
Could you try now? I've updated the requirements, which may make it work now!
