### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by AtomicPerception** [Bismuth-Consultancy-BV/MLOPs#106]
I'm not sure how this can be done, but as I download more models, I forget which ones are the best. Is there a way to add a rating system, or even a simple thumbs up to the model drop down to know which model I previously liked?

Even a number next to each model indicating how many diffusions it has kicked out might be a nice indicator that the model had been used extensively.

**Comment by Ambrosiussen** [comment]
This is not really possible because it depends on Houdini UI. What you could however do to remember which ones are preferred, is to save them as a preset on the node using the gear icon in the parm interface.
