### ISSUE TITLE
Apple M2 "No module named 'torch'" error

### ISSUE THREAD

**Issue by ChrisFriendly** [Bismuth-Consultancy-BV/MLOPs#111]
After the last Update it seems to go further but now it can't the torch.
Is there a torch version that work on Apple Silicon?

**Comment by ChrisFriendly** [comment]
is there a way to maybe use this?
[https://github.com/apple/ml-stable-diffusion](url)

**Comment by maxp-hover** [comment]
having this same error, but I'm on an Intel Mac
