### ISSUE TITLE
[RFE] Export Image Gamma Correction Toggle

### ISSUE THREAD

**Issue by AtomicPerception** [Bismuth-Consultancy-BV/MLOPs#119]
I started using MLOPS2 today. The first thing I noticed was the images were washed out. Tracking it down to the image utils, I connected a check box to the export_image node to allow gamma correction to be optional.

Here's my code change to mlops_image_utils.py
<code>def colors_numpy_array_to_pil(input_colors, gamma_correct=0):
    # Transpose into (width, height, channels)
    input_colors = input_colors.transpose(1, 2, 0)
    if gamma_correct!=0:
        # Gamma Correct
        input_colors = pow(input_colors, 1.0 / 2.2) #Pass float instead?
    # Convert to RGB space
    input_colors = (input_colors * 255).round().astype("uint8")
    return Image.fromarray(input_colors)</code>

Inside the HDA I altered the calling code.
<code># Export
gamma_correct = node.parent().parm("gamma_correct").evalAsInt()
image = mlops_image_utils.colors_numpy_array_to_pil(input_colors, gamma_correct)</code>

It might be better to simply pass along a float instead of a toggle. Then you could pass 1.0 for no gamma correct and 2.2 for full gamma correct..?

**Comment by Ambrosiussen** [comment]
Fixed in 3.0
