### ISSUE TITLE
[RFE] JPEG Quality

### ISSUE THREAD

**Issue by AtomicPerception** [Bismuth-Consultancy-BV/MLOPs#124]
Perhaps add a slider to the _export_image_ node to pass along a value for increasing the quality of images rendered in the JPEG format. Not sure if this is needed for other formats. It could be as simple as a toggle titled HQ.

Even just hard coding the maximum might be a good idea, instead of the 75% that PIL defaults to.

Here are some suggested modifications I've made to _image_export.py_ that seem to work.

pil_image.save(path, quality=95)
pil_image.save(path, quality=100, subsampling=0)
pil_image.save(path,, quality="maximum")

**Comment by Ambrosiussen** [comment]
Fixed in 3.0
