### ISSUE TITLE
Install Dependencies throwing subprocess error

### ISSUE THREAD

**Issue by hipsterette** [Bismuth-Consultancy-BV/MLOPs#130]
`Traceback (most recent call last):
  File "mlops_install", line 5, in <module>
  File "/Users/*****/Documents/MLOPs/scripts/python/mlops_utils.py", line 126, in install_mlops_dependencies
    pip_install(hou.text.expandString("$MLOPS/requirements.txt"), True, True)
  File "/Users/****/Documents/MLOPs/scripts/python/mlops_utils.py", line 364, in pip_install
    raise hou.Error(res[1].decode())
hou.Error:   error: subprocess-exited-with-error
  
 × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      /Applications/Houdini/Houdini19.5.752/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_distutils_hack/__init__.py:17: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
        warnings.warn(
      /Applications/Houdini/Houdini19.5.752/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
        warnings.warn("Setuptools is replacing distutils.")
      Traceback (most recent call last):
        File "<string>", line 2, in <module>

        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/6n/9xz_rjz946b80_8s2gw2jwkw0000gn/T/pip-install-k2hyvmzz/xformers_67ce5be12fa24c4786a46aadfad7bd4d/setup.py", line 23, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/6n/9xz_rjz946b80_8s2gw2jwkw0000gn/T/pip-install-k2hyvmzz/xformers_67ce5be12fa24c4786a46aadfad7bd4d/setup.py", line 23, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
`

**Comment by Huronsen** [comment]
I have the same issue.

**Comment by thomascour** [comment]
Same here
`Traceback (most recent call last):
  File "mlops_install", line 5, in <module>
  File "X:\AI/Stable Diffusion/MLOPs/scripts/python\mlops_utils.py", line 126, in install_mlops_dependencies
    pip_install(hou.text.expandString("$MLOPS/requirements.txt"), True, True)
  File "X:\AI/Stable Diffusion/MLOPs/scripts/python\mlops_utils.py", line 364, in pip_install
    raise hou.Error(res[1].decode())
hou.Error: C:\PROGRA~1\SIDEEF~1\HOUDIN~1.506\python310\lib\site-packages\_distutils_hack\__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
  Running command git clone --filter=blob:none --quiet https://github.com/Keith-Hon/bitsandbytes-windows.git 'C:\Users\thoma\AppData\Local\Temp\pip-install-gu84u8dx\bitsandbytes_d98542e03bbf40c4819db6ec8b356529'
  error: subprocess-exited-with-error`

`× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by codebot6000** [comment]
just popping in to say also receiving "setuptools is replacing distutils with houdini 20.0.506 on linux

**Comment by gzimmermann123** [comment]
Same error on clean 20.0.547 install on macOS

**Comment by gzimmermann123** [comment]
I went ahead and tried installing the requirements via pip install in the shell (instead of the shelf tool provided). I found 2 problems when running:

`pip install -r requirements.txt`

1. `pip install rembg[gpu]` failed for me on a Mac (M1). I needed to install the CPU version instead:
`pip install rembg`
or modify the requirements.txt and replace "rembg[gpu]" with "rembg"

2. halpecocotools would not build out of the box. I needed to do the following:

```
$ git clone https://github.com/HaoyiZhu/HalpeCOCOAPI.git
$ cd HalpeCOCOAPI/PythonAPI
```

edit halpecocotools/_mask.pyx:
replace "# distutils: sources = ../common/maskApi.c" with "# distutils: sources = common/maskApi.c"
according to this: #https://github.com/HaoyiZhu/HalpeCOCOAPI/commit/a603f16a911052dbbf0bbec516047918a957dd1f
thank you  @Ambrosiussen !

then finally 
`$ python3 setup.py build develop`

after that I was able to run all requirements again and all went well:

`pip install -r requirements.txt`

now I am not sure MLOPs are working now, this is just some progress report :-)

**Comment by giosampietro** [comment]
@gzimmermann123 thanks for finding a solution. I’m a bit lost when it comes to implementing the steps you described. You mention “ I went ahead and tried installing the requirements via pip install in the shell ” do you mean the internal houdini python shell? Would you be ok with posting a few extra steps/descruptions to make this solution (finally!) available also to pyhon noobs? 

@Ambrosiussen could the rembg[gpu] choice step be automated by the pip install process itself?

**Comment by gzimmermann123** [comment]
so basically instead of pressing that shelf tool inside Houdini that the MLOPs developer provide, you stay outside of Houdini in a shell and re-produce what that shell tool does. If you look closely at the code of that shelf tool, it basically boils down to go over the `requirements.txt` file that ships with the MLOPs repo and (pip) installs each package. By doing that in the shell you see at what packages it breaks. For me it was the 2 I mentioned in my post. In the shell you can simply do the steps I mentioned to get around the problems. Once pip install is done with all the packages you can start houdidni and the MLOPs should find all required python packages.

**Comment by gzimmermann123** [comment]
so more concretely: use the houdini shell or a system shell, cd to where you have the MLOPs repo downloaded and run:
`pip install -r requirements.txt`
Then see where it breaks! Maybe it's the same packages than for me.

**Comment by Ambrosiussen** [comment]
I have fixed the installing issues on Windows + Linux for H20. Please try now :)
If you are using older versions of Houdini please see: https://github.com/Bismuth-Consultancy-BV/MLOPs/releases

**Comment by MtDersvan** [comment]
Not working on Mac out of the box just yet.

Several lines need to change:
- `rembg[gpu]==2.0.54` –> `rembg==2.0.54` (gpu version is not supported)
- `xformers==0.0.21` not supported
- `chumpy @ git+https://github.com/mattloper/chumpy@51d5afd92a8ded3637553be8cef41f328a1c863a` not supported
- `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk` clang is hardcoded somewhere (probably in diffusers), so I had to manually link it to a newly installed `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk`
- `--use-pep517` parameter is needed for proper installation of a few packages (e.g. `basicsr==1.4.2`), so you have to change the line in `mlops_utils.py` to `cmd = ["hython", "-m", "pip", "install", "--use-pep517", "--target", os.path.join(PIP_FOLDER, "temp")]`

This will result in Houdini saying dependency are installed correctly. That said, "Download Model" results in Houdini crash with a `File Not Found` Error.

**Comment by noiseandsilence** [comment]
Is there any soution for xformers not being supported, is it ok to just eliminate it from the requirements file?
