### ISSUE TITLE
ControlNet spits out error first time using it and can't get past it!

### ISSUE THREAD

**Issue by oliverban** [Bismuth-Consultancy-BV/MLOPs#131]
Hi!

First of, thanks so much for creating this, super powerful! I consider myself a poweruser in A1111 and ComfyUI so all this is familiar territory. But the error I am getting with ControlNet is beyond my knowledge for now. Please read on.

I am playing around and I can generate images with my own models no problem. I then created a small scene with camera and created a Camera to Points node which works great, can see all the depth and normal info and all that (although SHADING is flipped on the X-axis, but that is beside the point here). I am using the Albedo (Cd) view as my viewer.

<img width="839" alt="houdini_WHELTVBYVD" src="https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/55516443/e66136ce-4d5b-4ea6-aac5-bac113c5ef22">

The problem starts when connecting a SD Controlnet Conditioning node after the camera to points node, there it starts automatically downloading the model chosen in the list into "...MLOPs\data\models\cache\models--lllyasviel--Annotators". Then the node spits out the error you can see in the screenshot.

<img width="704" alt="houdini_9y1y1zBxbq" src="https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/55516443/d6a93170-587a-4b98-afbb-33367225ecdc">

Any Ideas as to why I am getting that error? All the POWER of SD lies in ControlNet so would be super-awesome to get that working!

 Also, I thought it should download the controlnet models into the "models\lllyasviel\canny, depth etc" folder, no? Maybe that's the problem somehow?

Either way, any help is greatly appreciated!

**Comment by Ambrosiussen** [comment]
Hi, I fixed some issues in Controlnet Conditioning recently. Could you try latest? If you still get issues please reopen this ticket and attach the error + a file if possible :)

**Comment by oliverban** [comment]
> Hi, I fixed some issues in Controlnet Conditioning recently. Could you try latest? If you still get issues please reopen this ticket and attach the error + a file if possible :)

Hi Paul! Thanks for getting back. I'll check it out, I would love to be able to use SD a bit more seamlessly in Houdini, I am quite certain at this point that it is the future of rendering as well! I'll be revisiting this once my current job is over! <3
