### ISSUE TITLE
ValueError in diffusers dependency

### ISSUE THREAD

**Issue by Subtle1rony** [Bismuth-Consultancy-BV/MLOPs#133]
After installing dependencies and models successfully, I receive this error when placing the MLOPS SD Pipeline node.  

I am on windows 10 using Houdini 20.0.547 production build with houdini python 3.10.10

I tried previous versions on Houdini 19.5 with python 3.9 and was not able to get as far installing the the dependencies and models as I was on H20. Maybe it just fell behind over the holidays? It would be great if the readme had the exact versions of Houdini, python and git that are confirmed working. Thanks for any help!
```
Error 
Invalid source /obj/txt2img/sd_solver1/solver.
(Error: Python error: Traceback (most recent call last):
File "<stdin>", line 52, in <module>
File "C:\dev/MLOPS/scripts/python\sdpipeline\image_solve.py", line 183, in run
noise_pred = unet(
File "C:\dev\MLOPS\data\dependencies\python\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "C:\dev\MLOPS\data\dependencies\python\diffusers\models\unet_2d_condition.py", line 956, in forward
sample, res_samples = downsample_block(
File "C:\dev\MLOPS\data\dependencies\python\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "C:\dev\MLOPS\data\dependencies\python\diffusers\models\unet_2d_blocks.py", line 1086, in forward
hidden_states = attn(
File "C:\dev\MLOPS\data\dependencies\python\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "C:\dev\MLOPS\data\dependencies\python\diffusers\models\transformer_2d.py", line 315, in forward
hidden_states = block(
File "C:\dev\MLOPS\data\dependencies\python\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "C:\dev\MLOPS\data\dependencies\python\diffusers\models\attention.py", line 218, in forward
attn_output = self.attn2(
File "C:\dev\MLOPS\data\dependencies\python\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "C:\dev\MLOPS\data\dependencies\python\diffusers\models\attention_processor.py", line 420, in forward
return self.processor(
File "C:\dev\MLOPS\data\dependencies\python\diffusers\models\attention_processor.py", line 1006, in __call__
batch_size, sequence_length, _ = (
ValueError: too many values to unpack (expected 3)
). 
```

**Comment by gzimmermann123** [comment]
I am seeing the same error in the solver node inside the sd_solver. I am on H20.0.547 and macOS. I switched "coda" to "cpu" since I needed to do that on all nodes on Mac. But sd_solver still shows the error above. I was unable to find a solution so far. 

Anybody any ideas?

**Comment by Awlou** [comment]
Yep, very same issue here.
![image](https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/119785678/bdd2401c-3bbd-4167-bfe3-4726745b4e30)
Were either of you able to find a fix yet?

**Comment by tuseejee** [comment]
I noticed that 'encoder_hidden_states' in 'attention_processor.py' is atleast part of the problem. I'm able to get the sd_pipeline node to generate an image using all the node defaults and prompts.

The error goes away when I comment out lines 1006-1008, and add the following line:

>>> batch_size, sequence_length, _ = hidden_states.shape

I suspect the error happens because 'encoder_hidden_states' doesn't return a value, not even a value of 'None' when it has no value.  I don't know enough about how 'encoder_hidden_states ' is supposed to be handled, but hopefully this helps someone implement a fix.

**Comment by gzimmermann123** [comment]
cool thanks for the hint. I finally got around to take another look at this. You are right, I believe `encoder_hidden_states` is causing trouble here. We do need `batch_size` later in the code though, so I don't think we can just comment out the whole thing. I just replaced this:

```
batch_size, sequence_length, _ = (
hidden_states.shape if encoder_hidden_states is None else encoder_hidden_states.shape
)
```

with this:

`batch_size, sequence_length, _ = hidden_states.shape`

and that seems to work. I got an image in the sd pipeline example.

**Comment by sawframe** [comment]
I had the same error. I reverted back to H19.5.805. Python3.9.13. MLOPS- v2. 
Works now.

**Comment by howitzer99** [comment]
I had the same issue when attempting to run MLOPs v2 in Houdini 20.0.547.  Replacing each `batch_size` with the line from https://github.com/Bismuth-Consultancy-BV/MLOPs/issues/133#issuecomment-1891547890 worked.

For some reason, Houdini 19.5.605 will not work due to many python errors.  Hopefully this fix continue to keep H20 and MLOPs in a working state.

**Comment by sawframe** [comment]
@howitzer99 Thanks! I also now have H20 working after editing 

> I had the same issue when attempting to run MLOPs v2 in Houdini 20.0.547. Replacing each `batch_size` with the line from [#133 (comment)](https://github.com/Bismuth-Consultancy-BV/MLOPs/issues/133#issuecomment-1891547890) worked.
>

**Comment by Belisarius56** [comment]
Seems to work! Thanks!

**Comment by Ambrosiussen** [comment]
Latest commit fixed this!
