### ISSUE TITLE
NumPy Traceback When Launching Houdini 19.5.605 with MLOPS

### ISSUE THREAD

**Issue by howitzer99** [Bismuth-Consultancy-BV/MLOPs#137]
Fresh install of MLOPs using Houdini 19.5.605, but throwing a very long list of traceback errors upon launching with MLOPs enabled in packages.

Here's the header of the console errors, I can attach the whole log if more information is required:

  *** The NumPy version is: "1.26.3"
and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.
Original error was: No module named 'numpy.core._multiarray_umath'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.605/houdini/python3.9libs\viewerstate\utils.py", line 933, in register_pystate
    mod = importlib.import_module(module_name)
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.605\python39\lib\importlib\__init__.py", line 127, in import_module**

**Comment by Ambrosiussen** [comment]
MLOPs 3.0 only works with H20 or newer.
For older versions please use the corresponding releases: https://github.com/Bismuth-Consultancy-BV/MLOPs/releases
