### ISSUE TITLE
pycocotools-2.0.7-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by AhmedAburady** [Bismuth-Consultancy-BV/MLOPs#138]
I get this error when i try to install dependencies 

Traceback (most recent call last):
  File "mlops_install", line 5, in <module>
  File "E:\MLOPS2/scripts/python\mlops_utils.py", line 130, in install_mlops_dependencies
    pip_install(hou.text.expandString("$MLOPS/requirements.txt"), True, True)
  File "E:\MLOPS2/scripts/python\mlops_utils.py", line 435, in pip_install
    raise hou.Error(res[1].decode())
hou.Error:   Running command git clone --filter=blob:none --quiet https://github.com/mattloper/chumpy 'C:\Users\abora\AppData\Local\Temp\pip-install-e5gdwlwn\chumpy_d56ad991db014a8f8758e972cf094782'
  Running command git rev-parse -q --verify 'sha^51d5afd92a8ded3637553be8cef41f328a1c863a'
  Running command git fetch -q https://github.com/mattloper/chumpy 51d5afd92a8ded3637553be8cef41f328a1c863a
ERROR: pycocotools-2.0.7-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

**Comment by mnlrbr** [comment]
had the same issue and it was solved with a fresh python 3.12, Git and H20. Not sure if I overreactedm but it worked.

**Comment by Ambrosiussen** [comment]
What version of Houdini did you use?
MLOPs3.0 _only_ works on H20 and newer

**Comment by moo-bius** [comment]
For anyone who might still be having this issue make sure you have Houdini 20 **py3.10** not Houdini 20 py3.9.

**Comment by ReaperGrim94** [comment]
I'm getting the same error with Houdini 20 and Python 3.12 on windows 10.

I can't seem to get it to install dependencies properly
