### ISSUE TITLE
Torch/Python setup with Anaconda on Windows

### ISSUE THREAD

**Issue by ahemberger** [Bismuth-Consultancy-BV/MLOPs#15]
Hi there;

Might someone be able to elaborate on how this suite expects Python to be configured prior to installing? Does it use Houdini's Hython? 

I have the automatic1111 repo set up by way of Anaconda on my Windows machine, as I'd prefer a more flexible way to manage Python that having to muck around with a system Python installation. Is it possible for this tool to be used in this setup?

I ask because I installed this just now, and am trying to follow Entagma's "my first stable diffusion setup" video, but immediately get an error with the text_encoder node about "Torch not compiled with CUDA enabled"; the troubleshooting docs seem to assume (I think) that I have previously installed a system python that's compatible with stable diffusion, but I'd like to be able to configure this to use my Anaconda python if possible.

**Comment by usama-ghufran** [comment]
How did you finally fix this problem? I never had PyTorch installed and I installed CUDA after I started getting the error. 

Within Houdini in the Python shell 'torch' cannot seem to find cuda

```
>>> import torch
>>> torch.cuda.is_available()
False
```

**Comment by ahemberger** [comment]
Hey there;

The thing that was not obvious to me when trying to follow troubleshooting advice from the existing docs is what's actually happening with Python under the hood here. Maybe you've already figured this out, but this suite of tools leverages Hython, which ships with Houdini. So, there's no reliance on external/system/anaconda python versions. The troubleshooting mentions uninstalling Torch from system python, for reasons that aren't quite clear to me. 

In my case, what had happened is that I had installed Torch via Hython previously, and had done so without Cuda compatibility. So, when this repo tries to download dependencies, it found Torch already installed, skipped it, then claimed everything had been installed correctly. 

To fix it for me, then, I needed to uninstall my erroneous Torch package via Hython, then reinstall it via the shelf tool (actually, I dug into the shelf tool code and just ran the Hython pip install command directly, so I could understand what was happening...the shelf tool wasn't providing enough feedback for me to have a clear understanding what it was doing). 

You might try the same...uninstall Torch if it had been previously installed via Hython, then reinstall via the shelf tool (or, if you wanna do it manually, this:)

`hython -m pip install torch --index-url https://download.pytorch.org/whl/cu117`

**Comment by usama-ghufran** [comment]
That's helped! 
After installed the correct version of CUDA (11.7), I wasn't uninstalling torch. I was just deleting the folders in the Houdini/scripts/python folder. Installing torch didn't compile it with CUDA as there was already torch CPU version present.

Following your advice, I uninstalled torch and installed again and it works!
