### ISSUE TITLE
If Renderman is installed (and possibly also octane), Shelf install tools fail.

### ISSUE THREAD

**Issue by DarkOakSoftware** [Bismuth-Consultancy-BV/MLOPs#27]
Hython used in the shelf tools, actually invoke a totally different python install, namely the one in RM.

`C:\Program Files\Side Effects Software\Houdini 19.5.569\bin>hython -m pip list`
`.....snip....`
`File "C:\Program Files/Pixar/RenderManProServer-25.0\lib\python3.9\Lib\site-packages\pip\_vendor\certifi\core.py", line 51, in where
    _CACERT_PATH = str(_CACERT_CTX.__enter__())`
`  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.569\python39\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)`
`  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.569\python39\lib\importlib\resources.py", line 175, in _path_from_reader
    opener_reader = reader.open_resource(norm_resource)`
`  File "<frozen importlib._bootstrap_external>", line 1055, in open_resource`
`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files/Pixar/RenderManProServer-25.0\\lib\\python3.9\\Lib\\site-packages\\pip\\_vendor\\certifi\\cacert.pem'`

Because this python.exe is used instead, it constantly hits this missing file issue, and the shelf tool likely doesn't do actual work, installing 'nothing', and not reporting errors, resulting in a further failure a  ModuleNotFoundError: No module named 'huggingface_hub'. when Download Models is pressed.

However, invoking the python interpreter window directly, and querying where 'os.py' exists as an example shows:
`>>>os.__file__`
`C:\\PROGRA~1\\SIDEEF~1\\HOUDIN~1.569\\python39\\lib\\os.py`

Therefore, perhaps the use of "hython" for the shelf tool is not the best approach?

**Comment by Ambrosiussen** [comment]
This may be fixed now.

**Comment by DarkOakSoftware** [comment]
It is not fixed. Exactly the same issue. Hython invokes the python.exe in Renderman.
