### ISSUE TITLE
Feature Request: Image to Text (BLIP image captioning)

### ISSUE THREAD

**Issue by Faitel** [Bismuth-Consultancy-BV/MLOPs#40]
### BLIP image captioning
[mlops.BLIP_image_captioning.1.0.hdalc](https://raw.githubusercontent.com/Faitel/MLOPsLC/main/otls/mlops.BLIP_image_captioning.1.0.hdalc)
This experimental node converts an image represented as colored points into a textual description of its content. The description is stored as a point attribute called 'prompt' and is based on a machine learning model trained on image-caption pairs.

- Based on: [Salesforce/blip-image-captioning-base](https://huggingface.co/Salesforce/blip-image-captioning-base)
- More models: [BLIP](https://huggingface.co/models?other=blip)
- Model documentation: [BLIP](https://huggingface.co/docs/transformers/model_doc/blip)
- Interactive page: [Salesforce/BLIP](https://huggingface.co/spaces/Salesforce/BLIP)

![Blip Image Captioning](https://raw.githubusercontent.com/Faitel/MLOPsLC/main/help/images/screenshot_BLIP_image_captioning.png)

**Comment by Ambrosiussen** [comment]
Has been added!
