### ISSUE TITLE
Feature Request: Remove Background (RemBG)

### ISSUE THREAD

**Issue by Faitel** [Bismuth-Consultancy-BV/MLOPs#41]
### RemBG
[mlops.rembg_solver.1.7.hdalc](https://github.com/Faitel/MLOPsLC/blob/main/otls/mlops.rembg_solver.1.7.hdalc)
This node extracts and replaces background of image with solid color. 

- Based on: [KenjieDec/RemBG](https://huggingface.co/spaces/nielsr/CLIPSeg/tree/main)
- Model documentation: [danielgatis/rembg](https://github.com/danielgatis/rembg)
- Interactive page: [KenjieDec/RemBG](https://huggingface.co/spaces/KenjieDec/RemBG)
- Dependencies: rembg, rembg[gpu]

- !!! Copy MLOPs_rembg.json to Packages folder in Houdini's preferences directory
- !!! You have to install dependecies: Tab - MLOPs - RemBG - MLOPS RemBG Solver (Install)

![RemBG Install](https://raw.githubusercontent.com/Faitel/MLOPsLC/main/help/images/screenshot_RemBG_install.png)
![RemBG](https://raw.githubusercontent.com/Faitel/MLOPsLC/main/help/images/screenshot_RemBG.png)

**Comment by Ambrosiussen** [comment]
Added! Found in LORA branch
