### ISSUE TITLE
Feature Request: Compare two prompts by meaning (Semantic Similarity)

### ISSUE THREAD

**Issue by Faitel** [Bismuth-Consultancy-BV/MLOPs#42]
### Semantic Similarity
[mlops.st_semantic_similarity.1.0.hdalc](https://raw.githubusercontent.com/Faitel/MLOPsLC/main/otls/mlops.st_semantic_similarity.1.0.hdalc)
This node takes two textual prompts as input and returns a Similarity attribute between 0 and 1 indicating how closely related the prompts are in meaning. The score is based on a natural language processing model that compares the semantic content of the two prompts. 

- Based on: [tasks/sentence-similarity](https://huggingface.co/tasks/sentence-similarity)
- Model documentation: [SentenceTransformers ](https://www.sbert.net/)
- More models: [sentence-transformers](https://huggingface.co/models?library=sentence-transformers&pipeline_tag=sentence-similarity&sort=downloads)
- Dependencies: sentence-transformers

- !!! You have to install dependecies: Tab - MLOPs - SentenceTransformers  - MLOPS Semantic Similarity (Install)

![Semantic Similarity Install](https://raw.githubusercontent.com/Faitel/MLOPsLC/main/help/images/screenshot_ST_semantic_similarity_install.png)
![Semantic Similarity](https://raw.githubusercontent.com/Faitel/MLOPsLC/main/help/images/screenshot_ST_semantic_similarity.png)

**Comment by Pixelkram** [comment]
Implemented in lora_training branch. No need to use another semantic model, just uses the text encoder's output (thus using CLIP as semantic model).
