### ISSUE TITLE
Feature Request: Offset Image (SD Image Roll)

### ISSUE THREAD

**Issue by Faitel** [Bismuth-Consultancy-BV/MLOPs#43]
### SD Image Roll
[mlops.sd_image_roll.1.0.hdalc](https://raw.githubusercontent.com/Faitel/MLOPsLC/main/otls/mlops.sd_image_roll.1.0.hdalc)
This node shifts or offsets an input pixels along a specified axis.

- Based on: [Seamless Texture Inpainting](https://colab.research.google.com/drive/14gt9Z1wqQRS8jVfzJA1K9_PAYlXUAFrR?usp=sharing#scrollTo=WU3fAHi8DIhg)
- Method used: [Numpy Roll](https://numpy.org/doc/stable/reference/generated/numpy.roll.html)

![SD Image Roll](https://raw.githubusercontent.com/Faitel/MLOPsLC/main/help/images/screenshot_SD_image_roll.png)

**Comment by Ambrosiussen** [comment]
Added to Transform Image (LORA branch)
