### ISSUE TITLE
Feature Request: Repeat image inside its boundary (SD Image Tiling)

### ISSUE THREAD

**Issue by Faitel** [Bismuth-Consultancy-BV/MLOPs#44]
### SD Image Tiling
[mlops.sd_image_tiling.1.0.hdalc](https://raw.githubusercontent.com/Faitel/MLOPsLC/main/otls/mlops.sd_image_tiling.1.0.hdalc)
This node repeats images along a specified axis with preserving image dimensions.

- Method used: [Numpy Tile](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)
- Method used: [Skimage Resize](https://scikit-image.org/docs/stable/auto_examples/transform/plot_rescale.html)

![SD Image Tiling](https://raw.githubusercontent.com/Faitel/MLOPsLC/main/help/images/screenshot_SD_image_tiling.png)

**Comment by Ambrosiussen** [comment]
Added new node: Transfom Image which does this. (LORA Branch)
