### ISSUE TITLE
Feature Request: Dependency install function (MLOPs Utils)

### ISSUE THREAD

**Issue by Faitel** [Bismuth-Consultancy-BV/MLOPs#54]
Function to install specific dependency. To put as button parameter in custom nodes for example.

**Comment by Faitel** [comment]
or just to open Pip install window with predefined "Dependency:" field

**Comment by Ambrosiussen** [comment]
You can now use mlops_utils for this. See: https://github.com/Bismuth-Consultancy-BV/MLOPs/blob/main/scripts/python/mlops_utils.py#L67
