### ISSUE TITLE
Feature Request: MLOPs Camera for image (MLOPs shelf tool)

### ISSUE THREAD

**Issue by Faitel** [Bismuth-Consultancy-BV/MLOPs#55]
Shelf tool to create obj or lop orthographic camera which looks on image.

**Comment by Ambrosiussen** [comment]
What is this needed for? Please reopen ticket with reply :)

**Comment by Faitel** [comment]
When I'm turning Top view it shows image rotated on 90 degree. I thought about setting up camera to show image from top without persepctive and with right angle.
