### ISSUE TITLE
Feature Request: Meta tag data for generated images.

### ISSUE THREAD

**Issue by AtomicPerception** [Bismuth-Consultancy-BV/MLOPs#56]
If your looking for RFEs, a nice feature for the sd_export_image node would be an additional parm to allow meta tag data to be added to the generated image. The obvious text for the field would be the prompt and the model. Then you'd always have a path back to regenerate an image.

**Comment by AtomicPerception** [comment]
Extended code to implement prompt information into description metatag.
`# Exif codes list can be found here.
# https://github.com/hMatoba/Piexif/blob/master/piexif/_exif.py
exif = image.getexif()

# Simple implementation for native ascii tags.
#prompt = "fetch prompt from HDA field."    #270: {'name': 'ImageDescription', 'type': TYPES.Ascii},
prompt_positive = node.evalParm('prompt_positive')
prompt_negative = node.evalParm('prompt_negative')   
model = node.evalParm('model')   
settings = node.evalParm('settings')  
description = "POSITIVE: %s\n\nNEGATIVE:%s\n\n%s\n\n%s\n"%(prompt_positive,prompt_negative,model,settings)
exif[0x10E] = description`

**Comment by Ambrosiussen** [comment]
Added new parm with data that will be encoded
