### ISSUE TITLE
Feature Request: Add PYTHONPATH environment variable

### ISSUE THREAD

**Issue by Faitel** [Bismuth-Consultancy-BV/MLOPs#57]
{
            "HOUDINI_SCRIPT_PATH": "$MLOPS/data/dependencies/"
        },
        {
            "PYTHONPATH": "$MLOPS/data/dependencies/python"
        }

To force Houdini to search dependencies in mlops before in default houdini python folder. To avoid a situation where Houdini finds old versions of dependencies that come bundled with Houdini installation, such as numpy and pillow, before new ones.

**Comment by Ambrosiussen** [comment]
Fixed in LORA branch
