### ISSUE TITLE
Problem with the segmentation model/depth estimation model

### ISSUE THREAD

**Issue by XQQQ1995** [Bismuth-Consultancy-BV/MLOPs#66]
Hi, 
I have problem with the sd_controlnet_conditioning under segmentation/depth estimation mode(it works for edge detection though):
Here are some screenshots(I've checked the cache folder and it seems the model has alreday been downloaded), can anyone help me with this? Thanks in advance!
![image](https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/108653029/bdbf174e-6cb9-4f38-a17a-943dfe0f9aad)
![image](https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/108653029/ef2aea63-b6c6-4c65-b46e-58e70d0ae610)

**Comment by Ambrosiussen** [comment]
Has been fixed in Lora branch which will be released soon
