### ISSUE TITLE
Re Title Image Guidance Strength

### ISSUE THREAD

**Issue by AtomicPerception** [Bismuth-Consultancy-BV/MLOPs#67]
I know this is quite nit-picky, but shouldn't the label on the _MLOPs SD Scheduler_ read "Prompt Guidance Strength" instead of "Image Guidance Strength?" The value is opposite of what it does. When the image strength is 1.0, there is no image influence.

**Comment by Ambrosiussen** [comment]
Good point. Renaming to "Guide Image Deviation"
