### ISSUE TITLE
Feature request: store metadata downstream

### ISSUE THREAD

**Issue by luisfos** [Bismuth-Consultancy-BV/MLOPs#68]
would be very handy to pass all relevant data that contributed towards an image as an array of strings detail attribute
- prompts
- models used
- resolutions
- latent noise seed
- scheduler parameters
- controlnets used & their weights

**Comment by Ambrosiussen** [comment]
Hi you can use this node for that purpose:
![image](https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/23486196/8a23cbd4-3072-47c5-8105-a2110c58508a)
