### ISSUE TITLE
Enable resumable downloads or hf transfer

### ISSUE THREAD

**Issue by melMass** [Bismuth-Consultancy-BV/MLOPs#69]
Hey

So it seems like the [download wrapper](https://github.com/Bismuth-Consultancy-BV/MLOPs/blob/13b9b8ecc626c5c386d71376ae8cffae75ab2596/scripts/python/mlops_utils.py#L64)  doesn't use the keyword arg `resumable_download` ([see here](https://huggingface.co/docs/huggingface_hub/package_reference/file_download#huggingface_hub.snapshot_download.resume_download)) 

So I'm proposing to either use resumable downloads (a bit slower but resumable in case of a failed connection or a crash) or if not use maybe use [hf_transfer](https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfhubenablehftransfer).
The latter require both a new dependency and a new key in the package.json

**Comment by Ambrosiussen** [comment]
Added resume_download keyword
