### ISSUE TITLE
UserWarning: TypedStorage is deprecated

### ISSUE THREAD

**Issue by Pixelkram** [Bismuth-Consultancy-BV/MLOPs#7]
When starting Houdini with MLOPs installed I get this:

C:\Users/Mo/Documents/houdini19.5/scripts/python\transformers\modeling_utils.py:402: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(checkpoint_file, framework="pt") as f:
C:\Users/Mo/Documents/houdini19.5/scripts/python\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
C:\Users/Mo/Documents/houdini19.5/scripts/python\torch\storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
C:\Users/Mo/Documents/houdini19.5/scripts/python\safetensors\torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:

**Comment by Ambrosiussen** [comment]
Havent seen this happen in a while. Likely got fixed in transformers update
