### ISSUE TITLE
Houdini crashing when loading MLOPs SD Pipeline node

### ISSUE THREAD

**Issue by FuzzyCactusLogic** [Bismuth-Consultancy-BV/MLOPs#86]
Hey Guys, 

I've just installed MLOPs2. Houdini is crashing when I launch the SD Pipeline node (I tried this following the installation instructions). Maybe I did something wrong, or it's a bug?

Crash file and .txt crash file attached.

Operating System: Linux Mint 21.1
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-72-generic (64-bit)
Graphics Platform: X11
Processors: 64 × AMD Ryzen Threadripper 3970X 32-Core Processor
Memory: 251.6 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3090/PCIe/SSE2

[houdini_temp.zip](https://github.com/Bismuth-Consultancy-BV/MLOPs/files/11605389/houdini_temp.zip)

Many thanks for great work and making this available for all. Best.

**Comment by evanmathis** [comment]
Same issue on PopOS. - maybe a Linux specific issue?
I'll post the crash file when I'm back at that machine later tonight.

**Comment by evanmathis** [comment]
Here's the info on my system and the crash log:

Houdini FX Version 19.5.605

Operating System:         Pop!_OS 22.04 LTS
Number of Cores:          48
Physical Memory:          251.55 GB
Number of Screens:        2
    Screen 0:             3840 x 2160 at 0,0
    Work Area 0:          3840 x 2160 at 0,0
    Screen 0 DPI:         163.7
    Screen 1:             3840 x 2160 at 0,2160
    Work Area 1:          3840 x 2160 at 0,2160
    Screen 1 DPI:         157.4

Build platform:           linux-x86_64-gcc9.3
Python Version:           3.9
Qt Version:               5.15.2
USD Version:              22.05
USD git URL:              https://github.com/sideeffects/USD.git
USD git Revision:         484282ddfacfb79fafbc666907e3966b7bd15f96
UI Scale:                 1.500

OpenGL Vendor:            NVIDIA Corporation
OpenGL Renderer:          NVIDIA GeForce RTX 3090 Ti/PCIe/SSE2
OpenGL Version:           4.6.0 NVIDIA 525.105.17
OpenGL Shading Language:  4.60 NVIDIA
Detected:                 NVidia Consumer
                          24564 MB
                          525.105.17.0

[crash.untitled.three5_5401_log.txt](https://github.com/Bismuth-Consultancy-BV/MLOPs/files/11608639/crash.untitled.three5_5401_log.txt)

**Comment by trzanko** [comment]
Hello, 

Also getting an immediate crash on linux when putting down / trying to use the pipeline sd node. 

Here are my machine / os specs and crash log, have to enter here as screenshots as I'm using a remote machine. 
![Screenshot 2023-06-02 at 4 34 40 PM](https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/61357755/6f730024-4420-4cea-b369-995701d53bd8)
![Screenshot 2023-06-02 at 4 35 07 PM](https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/61357755/0039eae0-5819-4b1d-b31b-c043eb4f8d79)
![Screenshot 2023-06-02 at 4 35 16 PM](https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/61357755/2321db43-3e8c-4a87-a913-824309927332)

**Comment by Ambrosiussen** [comment]
Could you try updating to 3.0? I got it working on PopOS20.04
