### ISSUE TITLE
Installing MLOPS 2.0 breaks Numpy for regular Houdini

### ISSUE THREAD

**Issue by kfinlayson2k6** [Bismuth-Consultancy-BV/MLOPs#87]
So I have some python nodes for an RBF setup that calls numpy. After successfully installing 2.0 and the dependencies and doing some tests all is well. Close my MLOPS houdini session and open a new houdini session and my setup with a python node fails and reports numpy errors and quotes the MLOPS pythonpath in the error.

As soon as I removed the MLOPS.json from the packages folder and relaunched houdini.. all was well again.  

MLOPs 1.0 there were no issues. Both lived in harmony. 

Any workflow ideas? listing multiple paths?  it would be nice to not have to drag the .json in and out of the packages folder depending on what I am doing.

**Comment by melMass** [comment]
Hi,

I don't think anyone will be able to help with these info... can you provide the error and a little bit of info? OS, Houdini version etc...

**Comment by Ambrosiussen** [comment]
Please provide more info. Something like an error log :)
