### ISSUE TITLE
How to inpaint empty content ?

### ISSUE THREAD

**Issue by gregoiredelzongle** [Bismuth-Consultancy-BV/MLOPs#92]
Posting here following a discord discussion yesterday [there](https://discord.com/channels/925093472464146442/1098972025810337903/1113474801567289496)

I have an image with black spots, and I would like to **paint them out** properly, replacing it with **content aware** of the image around it. I also have a mask. I want to achieve something similar that what we see here : [link](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#inpainting)

My results for now are quite underwhelming with the following settings :

**Input image** (connected to the "images latents" third input of the Sd_Scheduler)
![input image](https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/9194561/4edd3d82-80bc-481f-9de2-3cefaaf20bc4)

**Input mask** (connected to the "mask input" of the scheduler)
![input mask](https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/9194561/01a9b768-46d4-445f-84d0-f562d460b302)

Prompt : "uv colorful checker"
Steps : 20
CFG : 7.5

**Result (guidance strength : 0.75)**
![result 1](https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/9194561/419f57ac-e5b8-449a-90e1-b6a7ef0b678a)

**Result (guidance strength : 1.0)**
![result 2](https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/9194561/28c6f5ef-9682-4440-b1a7-93b5828373f4)
It kinda works, but inpainted content is whiter for some reasons.

I've also tried with more conventional images (such as images generated from stable with the same prompt as an input)
Do you have any ideas with about how to improve my results ?

Cheers

**Comment by Ambrosiussen** [comment]
Hi, the next version of MLOPs supports the inpainting controlnets :)
