### ISSUE TITLE
Segmentation options unavailable

### ISSUE THREAD

**Issue by darkmythst** [Bismuth-Consultancy-BV/MLOPs#94]
segment_anything_model doesn't seem to have adjustment parameters for segmenting. 
<img width="530" alt="image" src="https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/97998238/17cb7b8a-5ad7-43b3-a7e5-bce4880f2a5d">

**Comment by Ambrosiussen** [comment]
Closing because its a duplicate issue of https://github.com/Bismuth-Consultancy-BV/MLOPs/issues/81
