### ISSUE TITLE
Apple Chip M2 error message

### ISSUE THREAD

**Issue by ipixart** [Bismuth-Consultancy-BV/MLOPs#98]
ERROR: Could not find a version that satisfies the requirement xformers==0.0.19 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.16rc424, 0.0.16rc425, 0.0.16, 0.0.20.dev539, 0.0.20.dev540, 0.0.20, 0.0.21.dev541, 0.0.21.dev542)
ERROR: No matching distribution found for xformers==0.0.19

**Comment by Eranio-bit** [comment]
I have the same issue on Mac. Please let me know if you find a solution for it.

**Comment by ChrisFriendly** [comment]
anyone found a solution for this issue yet?

**Comment by Eranio-bit** [comment]
Hey. No, I haven't opened mlops for a while. I had other issues with licensing problems that seem to be related to the os of the mac...I don't really know and don't have the expertise to say who is at fault but I just need to say the experience of Houdini in general on mac is awful so far.

**Comment by Eranio-bit** [comment]
> anyone found a solution for this issue yet?

I will try tomorrow

**Comment by pcolton** [comment]
same error here

**Comment by pcolton** [comment]
I resolved this error by cloning from repo instead of downloading the .zip. The repo has a newer requirements.txt file
