### ISSUE TITLE
No matching distribution found for scipy==1.10.1, when clicked "Install Dependences"

### ISSUE THREAD

**Issue by twink13** [Bismuth-Consultancy-BV/MLOPs#99]
Hi, when i click "Install Dependences", and wait a miute, I got a error with:
```python
Traceback (most recent call last):
  File "mlops_install", line 5, in <module>
  File "D:/Projects/MLOPs/scripts/python\mlops_utils.py", line 125, in install_mlops_dependencies
    pip_install(hou.text.expandString("$MLOPS/requirements.txt"), True, True)
  File "D:/Projects/MLOPs/scripts/python\mlops_utils.py", line 301, in pip_install
    raise hou.Error(res[1].decode())
hou.Error:   Running command git clone --filter=blob:none --quiet https://github.com/patrickvonplaten/controlnet_aux 'C:\Users\Admin\AppData\Local\Temp\houdini_temp\pip-install-iqsw5nic\controlnet-aux_42b9b3febb6b49a99104417713dfd685'
  Running command git rev-parse -q --verify 'sha^940828671b85fed4432a9862aded391b7e927b8f'
  Running command git fetch -q https://github.com/patrickvonplaten/controlnet_aux 940828671b85fed4432a9862aded391b7e927b8f
  Running command git checkout -q 940828671b85fed4432a9862aded391b7e927b8f
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/diffusers 'C:\Users\Admin\AppData\Local\Temp\houdini_temp\pip-install-iqsw5nic\diffusers_f643b747c3ac4ef68d04b3756dc77c2e'
  Running command git rev-parse -q --verify 'sha^2858d7e15eaf445ec37fc77b204a85f84affbeef'
  Running command git fetch -q https://github.com/huggingface/diffusers 2858d7e15eaf445ec37fc77b204a85f84affbeef
  Running command git checkout -q 2858d7e15eaf445ec37fc77b204a85f84affbeef
ERROR: Ignored the following versions that require a different python version: 1.10.0 Requires-Python <3.12,>=3.8; 1.10.0rc1 Requires-Python <3.12,>=3.8; 1.10.0rc2 Requires-Python <3.12,>=3.8; 1.10.1 Requires-Python <3.12,>=3.8; 1.11.0rc1 Requires-Python <3.13,>=3.9; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11; 1.9.0 Requires-Python >=3.8,<3.12; 1.9.0rc1 Requires-Python >=3.8,<3.12; 1.9.0rc2 Requires-Python >=3.8,<3.12; 1.9.0rc3 Requires-Python >=3.8,<3.12; 1.9.1 Requires-Python >=3.8,<3.12; 1.9.2 Requires-Python >=3.8; 1.9.3 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement scipy==1.10.1 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0rc1, 1.7.0rc2, 1.7.0, 1.7.1, 1.7.2, 1.7.3)
ERROR: No matching distribution found for scipy==1.10.1
``` 
Do you know what is means? Thanks.

**Comment by melMass** [comment]
You will need to provide more info, I can guess that you are under windows from the path but that's about it.

What Houdini version are you on?

**Comment by Hantritor** [comment]
I have exact the same issue.
Houdini version 19.5.493

**Comment by glennsuber** [comment]
I am having the same issue, log below.

I am running ubuntu 22.04, houdini 19.5.605

I currently have other versions of python and pip installed on the machine, I have checked the PYTHONPATH which does not exist other than in the MLOPS.json file, as such, I don't believe the conflict is happening there, but I could be wrong.

Happy to run more tests if given some further instruction

Traceback (most recent call last):
  File "mlops_install", line 5, in <module>
  File "/media/bananas/resources/MLOPS2/MLOPs/scripts/python/mlops_utils.py", line 125, in install_mlops_dependencies
    pip_install(hou.text.expandString("$MLOPS/requirements.txt"), True, True)
  File "/media/bananas/resources/MLOPS2/MLOPs/scripts/python/mlops_utils.py", line 301, in pip_install
    raise hou.Error(res[1].decode())
hou.Error: cat: /sys/devices/virtual/dmi/id/board_{vendor,name,version}: No such file or directory
sh: 1: ethtool: not found
sh: 1: ethtool: not found
  Running command git clone --filter=blob:none --quiet https://github.com/patrickvonplaten/controlnet_aux /tmp/pip-install-kqg_mc8d/controlnet-aux_51752b2f28c3414f84cca0bc94fffb07
  Running command git rev-parse -q --verify 'sha^845161d1deac8c4f0a8f9df0c9dc355fcc2d0830'
  Running command git fetch -q https://github.com/patrickvonplaten/controlnet_aux 845161d1deac8c4f0a8f9df0c9dc355fcc2d0830
  Running command git checkout -q 845161d1deac8c4f0a8f9df0c9dc355fcc2d0830
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/diffusers /tmp/pip-install-kqg_mc8d/diffusers_6a0b5030bda144279ce0cb27f2b286f4
  Running command git rev-parse -q --verify 'sha^2858d7e15eaf445ec37fc77b204a85f84affbeef'
  Running command git fetch -q https://github.com/huggingface/diffusers 2858d7e15eaf445ec37fc77b204a85f84affbeef
  Running command git checkout -q 2858d7e15eaf445ec37fc77b204a85f84affbeef
ERROR: Ignored the following versions that require a different python version: 1.10.0 Requires-Python <3.12,>=3.8; 1.10.0rc1 Requires-Python <3.12,>=3.8; 1.10.0rc2 Requires-Python <3.12,>=3.8; 1.10.1 Requires-Python <3.12,>=3.8; 1.11.0rc1 Requires-Python <3.13,>=3.9; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11; 1.9.0 Requires-Python >=3.8,<3.12; 1.9.0rc1 Requires-Python >=3.8,<3.12; 1.9.0rc2 Requires-Python >=3.8,<3.12; 1.9.0rc3 Requires-Python >=3.8,<3.12; 1.9.1 Requires-Python >=3.8,<3.12; 1.9.2 Requires-Python >=3.8; 1.9.3 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement scipy==1.10.1 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0rc1, 1.7.0rc2, 1.7.0, 1.7.1, 1.7.2, 1.7.3)
ERROR: No matching distribution found for scipy==1.10.1

**Comment by twink13** [comment]
> You will need to provide more info, I can guess that you are under windows from the path but that's about it.
> 
> What Houdini version are you on?

Yes, in WIndows, Houdini 19.0.622.

**Comment by glennsuber** [comment]
Looks like this could be an issue if you have the python 3.7 build of houdini installed, try the regular 3.9 version. Python dependencies look like they are not supported for python 3.7

**Comment by Hantritor** [comment]
I'm on Python 3.9

**Comment by Ambrosiussen** [comment]
For those getting the error on Python3.9, could you try now on latest?
For those on 3.7, this is not supported, sorry.
